FROM python:3.12-slim

RUN apt-get update && apt-get install -y curl git build-essential libpq-dev zlib1g-dev

# Install uv
COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

WORKDIR /code

COPY ./README.md ./
COPY ./pyproject.toml ./
RUN uv pip install --system --no-cache .

COPY ./src ./src

ENV PYTHONPATH=/code
